steps:
  # Étape 1: Construire l'image Docker
  # On utilise le builder Docker de Cloud Build.
  - name: 'gcr.io/cloud-builders/docker'
    # 'PROJECT_ID' est une variable fournie par Cloud Build, pas besoin de la changer.
    # 'REPO_NAME' est le nom que vous donnerez à votre dépôt Artifact Registry.
    # 'SERVICE_NAME' est le nom de votre service (ex: figma-mcp-server).
    # 'COMMIT_SHA' est une variable fournie par Cloud Build, c'est le hash du commit git.
    args:
      [
        'build',
        '-t',
        'europe-west9-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}',
        '.',
        '-f',
        'Dockerfile'
      ]

  # Étape 2: Pousser l'image vers Artifact Registry
  # Une fois l'image construite, on la pousse dans le registre pour la stocker.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west9-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}']

  # Étape 3: Déployer sur Cloud Run
  # On déploie la nouvelle image sur Cloud Run avec les variables d'environnement
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'europe-west9-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '--region'
      - 'europe-west9'
      # Variables d'environnement depuis Secret Manager
      - '--set-secrets'
      - 'FIGMA_API_KEY=figma-api-key:latest'
      # Variables d'environnement classiques
      - '--set-env-vars'
      - 'NODE_ENV=production,GOOGLE_CLOUD_PROJECT=${PROJECT_ID},GOOGLE_CLOUD_LOCATION=europe-west9,LLM_MODEL=gemini-2.0-flash-lite,LLM_TEMPERATURE=0.9'
      # Secrets pour l'authentification LLM
      - '--set-secrets'
      - 'GOOGLE_CLIENT_EMAIL=llm-service-account-email:latest,GOOGLE_PRIVATE_KEY=llm-service-account-key:latest'
      # --allow-unauthenticated permet de rendre le service accessible publiquement
      # Si votre API doit être privée, il faudra changer cette option
      - '--allow-unauthenticated'

# On spécifie quelles images doivent être stockées dans Artifact Registry après le build.
images:
  - 'europe-west9-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'

# Options pour la substitution de variables
# Vous pourrez définir ces variables au moment de créer le trigger Cloud Build
substitutions:
  _SERVICE_NAME: figma-mcp-server
  _REPO_NAME: figma-mcp-repo

options:
  logging: CLOUD_LOGGING_ONLY
